"""Creating tables

Revision ID: c0752fb1d28d
Revises: 
Create Date: 2024-02-24 15:56:52.960842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0752fb1d28d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_departmentUsed', table_name='usage')
    op.drop_index('ix_usage_endTime', table_name='usage')
    op.drop_index('ix_usage_id', table_name='usage')
    op.drop_index('ix_usage_startTime', table_name='usage')
    op.drop_table('usage')
    op.drop_index('ix_lesson_code', table_name='lesson')
    op.drop_index('ix_lesson_grade', table_name='lesson')
    op.drop_index('ix_lesson_id', table_name='lesson')
    op.drop_index('ix_lesson_name', table_name='lesson')
    op.drop_table('lesson')
    op.drop_index('ix_sinif_building', table_name='sinif')
    op.drop_index('ix_sinif_faculty', table_name='sinif')
    op.drop_index('ix_sinif_floor', table_name='sinif')
    op.drop_index('ix_sinif_id', table_name='sinif')
    op.drop_table('sinif')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sinif',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sinif_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('faculty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('building', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sinif_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_sinif_id', 'sinif', ['id'], unique=False)
    op.create_index('ix_sinif_floor', 'sinif', ['floor'], unique=False)
    op.create_index('ix_sinif_faculty', 'sinif', ['faculty'], unique=False)
    op.create_index('ix_sinif_building', 'sinif', ['building'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lesson_pkey')
    )
    op.create_index('ix_lesson_name', 'lesson', ['name'], unique=False)
    op.create_index('ix_lesson_id', 'lesson', ['id'], unique=False)
    op.create_index('ix_lesson_grade', 'lesson', ['grade'], unique=False)
    op.create_index('ix_lesson_code', 'lesson', ['code'], unique=False)
    op.create_table('usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departmentUsed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('startTime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endTime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sinif_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sinif_id'], ['sinif.id'], name='usage_sinif_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usage_pkey')
    )
    op.create_index('ix_usage_startTime', 'usage', ['startTime'], unique=False)
    op.create_index('ix_usage_id', 'usage', ['id'], unique=False)
    op.create_index('ix_usage_endTime', 'usage', ['endTime'], unique=False)
    op.create_index('ix_usage_departmentUsed', 'usage', ['departmentUsed'], unique=False)
    # ### end Alembic commands ###
